"""add_ratings_to_borrow_request

Revision ID: 39c9af6a8397
Revises: 641076744664
Create Date: 2026-07-11 05:04:45.798800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c9af6a8397'
down_revision: Union[str, None] = '641076744664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('borrower_rating', sa.Integer(), nullable=True))
    op.add_column('borrow_requests', sa.Column('lender_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_requests', 'lender_rating')
    op.drop_column('borrow_requests', 'borrower_rating')
    # ### end Alembic commands ###
