"""add_borrow_request_id_to_complaints

Revision ID: 641076744664
Revises: 0001_add_google_oauth
Create Date: 2026-07-10 17:34:09.284136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641076744664'
down_revision: Union[str, None] = '0001_add_google_oauth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('borrow_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'borrow_requests', ['borrow_request_id'], ['id'])
    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'borrow_request_id')
    # ### end Alembic commands ###
