"""add push and email notification prefs

Revision ID: 6808ff6cbba2
Revises: 6707ff6cbba1
Create Date: 2026-08-11 11:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6808ff6cbba2'
down_revision: Union[str, None] = '6707ff6cbba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'push_notifications')
    # ### end Alembic commands ###
