"""add_indexes_to_resource

Revision ID: 999999999999
Revises: 5dad096407b8
Create Date: 2026-08-12 19:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999999999999'
down_revision: Union[str, None] = '5dad096407b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resources_average_rating'), 'resources', ['average_rating'], unique=False)
    op.create_index(op.f('ix_resources_total_borrows'), 'resources', ['total_borrows'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_total_borrows'), table_name='resources')
    op.drop_index(op.f('ix_resources_average_rating'), table_name='resources')
    # ### end Alembic commands ###
