"""add_wanted_request_id_to_borrow_request

Revision ID: a7c3e9ed1944
Revises: 2060cdf0bdda
Create Date: 2026-07-19 11:00:27.099700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c3e9ed1944'
down_revision: Union[str, None] = '2060cdf0bdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('wanted_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'borrow_requests', 'wanted_requests', ['wanted_request_id'], ['id'])
    op.create_index(op.f('ix_wanted_offers_id'), 'wanted_offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wanted_offers_id'), table_name='wanted_offers')
    op.drop_constraint(None, 'borrow_requests', type_='foreignkey')
    op.drop_column('borrow_requests', 'wanted_request_id')
    # ### end Alembic commands ###
