"""add_is_suspended

Revision ID: c7f260b43a82
Revises: a7c3e9ed1944
Create Date: 2026-07-19 11:34:33.596451

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.exc import ProgrammingError
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f260b43a82'
down_revision: Union[str, None] = 'a7c3e9ed1944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import inspect

def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    has_is_suspended = False
    for col in inspector.get_columns("users"):
        if col["name"] == "is_suspended":
            has_is_suspended = True
            break
            
    if not has_is_suspended:
        op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    # ### end Alembic commands ###
