"""add_wanted_request_model

Revision ID: e8049efbe935
Revises: 39c9af6a8397
Create Date: 2026-07-11 05:59:21.029385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8049efbe935'
down_revision: Union[str, None] = '39c9af6a8397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wanted_requests_id', table_name='wanted_requests')
    op.drop_table('wanted_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanted_requests',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_fulfilled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='wanted_requests_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wanted_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wanted_requests_pkey')
    )
    op.create_index('ix_wanted_requests_id', 'wanted_requests', ['id'], unique=False)
    # ### end Alembic commands ###
