name: Fetch EC2 Logs

on:
  push:
    branches:
      - akarsh

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch logs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd College-Resource-Sharing-System
            docker compose -f docker-compose.prod.yml logs backend --tail 100
